# Setup
title:       Personalized Graph-Based Retrieval Benchmark for LLMs (PGraphRAG)
tagline:      PGraphRAG
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author: 
  name: Steven Au
  url:  https://github.com/Prowo

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
