# Setup
title:       PGraphRAG
tagline:      Personalized Graph-Based Retrieval
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author: Steven Au
  name:     

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
